couchbaselabs/jenkins-sdk

config/job-config.yaml
src/com/couchbase/perf/sdk/stages/BuildDockerPythonSDKPerformer.groovy
src/com/couchbase/perf/sdk/stages/InitialiseSDKPerformer.groovy
src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/tools/network/NetworkUtil.groovy
src/com/couchbase/tools/performer/BuildDockerPythonPerformer.groovy
src/com/couchbase/versions/DotNetVersions.groovy
src/com/couchbase/versions/GoVersions.groovy
src/com/couchbase/versions/JVMVersions.groovy
src/com/couchbase/versions/PythonVersions.groovy

* The requirements file for python performer is now edited correctly to specify a version or building from source from master or a commit SHA
* `JVMVersions.read()` moved to new class `NetworkUtil`. Added `readJson()` and `readXml()` convenience methods

PYCBC-1397: Support for Python performer

---

config/job-config.yaml
src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/versions/CppVersions.groovy

* Added C++ snapshot and beta-4 in job-config
* Changed the labels for snapshots so they look like `1.0.0-20230201.125654-1437691` (`<version>-<date>.<time>-<sha>`). Version 1.0.0 is hardcoded for now

Add C++ performer back in job-config and change version label for C++ snapshots

---

config/job-config.yaml
src/com/couchbase/perf/shared/config/ConfigParser.groovy

* Added `concurrencyMechanism` tunable for Python in job-config.yaml
* Changed `includeVariablesThatApplyToThisRun()` to include all implementations for a language if version is not specified

PYCBC-1437: Use tunable to tell Python performer which concurrency mechanism to use

---

src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/versions/CppVersions.groovy
src/com/couchbase/versions/ImplementationVersion.groovy

Changes:
- Made `ImplementationVersion` implement the `Comparable` interface which makes it easier to get the max, do a sort etc.
- Defined `compareTo` by following the comparison rules on the [SemVer spec](https://semver.org/#spec-item-11) - the difference with before is that pre-release fields are also taken into account when comparing versions (could this change break any existing functionality?)
- Removed the hard-coded C++ snapshot version as it's no longer necessary now that pre-release fields are taken into account when comparing implementation versions and with the new C++ release tags

CBD-5323: Follow semver spec for comparing impl versions & remove C++ snapshot version hard-coding

---

config/job-config.yaml
src/com/couchbase/versions/CppVersions.groovy

Exclude the unsupported dp/beta C++ releases when `getAllReleases()` is called, which allows job-config to be more concise

CBD-5457: Always exclude unsupported C++ versions

---

src/com/couchbase/tools/tags/TagProcessor.groovy

The tag processor was trimming the line but not the marker, which can have leading whitespace when the code is indented in Python. This meant that `includedAlready` would never evaluate to true for indented code

PYCBC-1543: Fix tag processor not uncommenting indented code in Python

---

src/com/couchbase/tools/performer/BuildDockerDotNetPerformer.groovy

Motivation
-----------
The FIT performer needs to include the new Couchbase.NetClient project in its solution and project file in order to locate the correct Couchbase.Cluster class.
This will break the performance build when checking out SDK versions < 3.4.14 using the latest .NET FIT Performer.

NCBC-3585: Allow backwards compatibility to performance builds with new FIT performer project

---

config/job-config.yaml
src/com/couchbase/tools/performer/BuildDockerGoPerformer.groovy

Currently the option to build main was ignored, which meant that the Go SDK version specified in the committed go.mod file was used instead of the latest commit on master. Will add a new `SDK_VERSION` build parameter to the Go Dockerfile to support this

Support BuildMain in BuildDockerGoPerformer

---

src/com/couchbase/tools/performer/BuildDockerNodePerformer.groovy

We're currently appending `^` at the start of the specified build version, which allows npm to install the latest minor/patch of the specified SDK version. This change forces npm to install the exact SDK version specified.

Fix Node HasVersion build

---

src/com/couchbase/tools/performer/BuildDockerCppPerformer.groovy
src/com/couchbase/tools/performer/BuildDockerPythonPerformer.groovy
src/com/couchbase/tools/performer/BuildDockerRubyPerformer.groovy
src/com/couchbase/tools/performer/BuildPerformer.groovy

Adds the `--docker-build-args` option which takes space separated build args, e.g. `ARG1=foo ARG2=bar`. Currently enabled for C++, Python, Ruby.

Add option to set docker build arguments via `buildPerformer` command

---

README.md
TAG_SYNTAX.md
build.gradle
src/com/couchbase/tools/tags/TagProcessor.groovy
src/com/couchbase/tools/tags/TagProcessorV0.groovy
src/com/couchbase/tools/tags/TagProcessorV1.groovy
test/src/com/couchbase/tools/tags/TagProcessorV1Test.groovy

Ground-up rewrite of the tag processor to support nested conditions and if/else.
The processor now uses single-line comments to skip code. This is a potentially breaking change for performer code that relied on the previous behavior of using multi-line comments. To mitigate this, users must opt-in on a per-file basis by using at least one `if` tag.
Restoration is now a separate function. It's really simple: it just replaces all instances of "// [SKIPPED]" with an empty string, and puts "activated" code back the way it was before.
`processTags` no longer has an optional "restore" parameter. I didn't see it used anywhere; please confirm!

Supported nested tags and if/else

---

src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/versions/CppVersions.groovy
src/com/couchbase/versions/GithubVersions.groovy
src/com/couchbase/versions/PythonVersions.groovy
src/com/couchbase/versions/RubyVersions.groovy
src/com/couchbase/versions/Versions.groovy

Currently snapshot labels for C++ are formatted as (for example) `1.0.0-dp.13-20240306.194113-7ee5a53`. According to semver, anything after the first `-` is treated as a set of dot separated identifiers which are compared to sort versions. This means that `13-20240306` is one of those identifiers. As it contains a non-numeric character (`-`), this identifier is being compared lexically based on ASCII order which results in incorrect ordering for the C++ perf results.
* If the fetched latest version is already a pre-release version (e.g. `dp` or `rc`), append any additional pre-release identifiers using `.` instead of `-` to ensure that the date forms its own identifier.
* Use `+` instead of `-` to append the commit SHA. This ensures that it is treated as build metadata not used for …

Fix formatting of C++ snapshot versions

---

TAG_SYNTAX.md

to reflect how `if/else` is used in practice.
The previous example wasn't ideal, since the
unprocessed source would always throw an exception.

Update tag syntax example

---

src/com/couchbase/perf/shared/main/main.groovy

After a recent change, the SHA is now appended as build metadata with a `+` for Python, C++ and Ruby. Fix the code that extracts it when creating a `PerfConfig.Implementation`.

Fix SHA parsing for Ruby/Python/C++ snapshot versions

---

src/com/couchbase/tools/performer/BuildDockerCppPerformer.groovy

We don't need the tag processor to be called for C++, since we use C++'s own preprocessor directives

Don't run tag processor for C++

---

src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/versions/CppVersions.groovy
src/com/couchbase/versions/GithubVersions.groovy
src/com/couchbase/versions/ImplementationVersion.groovy
test/src/com/couchbase/versions/CppVersionsTest.groovy

* In pre-release identifiers of snapshot versions, use the number of commits since the last tagged release, instead of date/time
* After a non-RC release (i.e. after a tag without pre-release identifiers), increment the patch. This ensures that these snapshot versions have higher precedence than the release, according to semver sorting rules.
* For snapshot builds where the commit is a tagged version, don't append the commit SHA or number of commits since tag (which would be 0) to the version
* Update `ImplementationVersion.compareTo()` to ignore the leading `-` and the build metadata (anything following a `+`)
For example:
```
1.0.2, 1.0.3-4+ae5370d, 1.0.3-rc.1, 1.0.3-rc.1.1+31fb90e, 1.0.3-rc.2, 1.0.3, 1.0.4-3+aba976e
```
Under the existing naming scheme, `1.0.4-3+aba976e` would be …

Update C++ snapshot version naming scheme

---

src/com/couchbase/tools/performer/BuildPerformer.groovy

SDK 3.4.5-rc2 mistakenly added .net8 to the target frameworks, which is removed in the release 3.4.5 until 3.4.14-rc4. jenkins-sdk is using the Dockerfile for .NET 6 only with 3.4.5-rc2(anything below 3.4.14).
This specific tag should be skipped for testing.

SDKQE-3477: Skip FIT-testing .NET SDK 3.4.5-rc2

---

src/com/couchbase/tools/performer/BuildDockerGoPerformer.groovy
src/com/couchbase/tools/performer/BuildPerformer.groovy
src/com/couchbase/tools/performer/VersionToBuild.groovy

* Add support for `BuildGerrit` in `BuildDockerGoPerformer` that uses the `SDK_GERRIT_REF` docker build argument (needs the relevant [performer change](https://review.couchbase.org/c/transactions-fit-performer/+/219970))
* The tag processor now only processes files with the `.go` file extension
* We now longer throw an exception if `BuildSha` or `BuildShaVersion` is provided – they are already supported
* Allow passing free-form docker build arguments
* Add `BuildGerritVersion`, which allows both specifying a gerrit patch and running the tag processor – similar to `BuildShaVersion`
* Add `HasGerrit` to allow grouping `BuildGerrit` & `BuildGerritVersion` together

GOCBC-1682: Support BuildGerrit for Go performer

---

src/com/couchbase/versions/CppVersions.groovy
src/com/couchbase/versions/GithubVersions.groovy
test/src/com/couchbase/versions/CppVersionsTest.groovy

This changes how we find the "nearest release". Instead of getting the tag with the highest value according to semver sorting rules, we find the tag that is the least amount of commits away from the specified commit, on the specified branch.
Another change is that we now increment the dot-minor for snapshots on `main` that are not after a pre-release tag.

SDKQE-3529: Update C++ snapshot label logic to take into account new branching approach

---

config/job-config.yaml

The latest .NET minor specified in the FIT-perf job config is 3.4.X, meaning the latest version displayed as non-snapshot on the performance dashboard is 3.4.14.
- Added minor 3.5.X and 3.6.X

NCBC-3966: Update FIT-PERF job-config.yaml to add newer versions the SDK

---

src/com/couchbase/tools/performer/BuildPerformer.groovy

We already have the requirements in place to specify free-form docker build params for Go and Go columnar. We need update the parameter validation to allow that.

Allow docker-build-args buildPerformer param for Go

---

src/com/couchbase/tools/performer/BuildDockerGoPerformer.groovy

Docker caches the build steps, including the `go get github.com/couchbase/gocb/v2@master` step, which builds that the performer build will not necessarily use the latest version of master. We should provide the SHA of the latest commit to the docker build to prevent this.

[Go] Provide commit SHA to docker build for BuildMain to prevent use of cached main

---

config/job-config.yaml
src/com/couchbase/perf/sdk/stages/InitialiseSDKPerformer.groovy
src/com/couchbase/perf/sdk/stages/StartDockerImageCppSDKPerformer.groovy

Changes
=======
* Allow some time before killing the C++ docker container so that if a crash has occurred the gdb output can be pushed to stderr
* Remove C++ performer from transaction read load until CXXCBC-678 is fixed

Update C++ performer config to enable output of crash dump

---

config/job-config.yaml

Older Java dot-minor releases build successfully in [fit-validate-performers-build](https://sdk.jenkins.couchbase.com/job/fit/job/fit-validate-performers-build/), so they should probably be added.
Kotlin snapshots are also being verified & build successfully so it appears that it can be re-enabled.

Add Kotlin snapshots & Java releases to job-config

---

config/job-config.yaml

version 3.7.x was added twice, so made one 3.8.x.

Add dotnet 3.8.X to peformance website

---

.gitignore
src/com/couchbase/perf/sdk/stages/BuildDockerRustSDKPerformer.groovy
src/com/couchbase/perf/sdk/stages/InitialiseSDKPerformer.groovy
src/com/couchbase/perf/shared/main/main.groovy
src/com/couchbase/tools/performer/BuildDockerRustPerformer.groovy
src/com/couchbase/versions/GithubVersions.groovy
src/com/couchbase/versions/RustVersions.groovy

Changes:
- Added `getSnapshotAttributesFromCommit` function, to more accurately describe when native Rust SDK development started, as the repo is shared/merged with the deprecated non-native Rust SDK
- Change snapshot builds to pull from Github instead of Cargo
- Small misc fixes
Note: Pre developer preview versions will be labelled `0.1.0-<Commits From Initial>+<SHA>`

RSCBC-137: Add Rust to Perf dashboard
